import React from 'react';
import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../App';
import renderWithRouter from './helpers/renderWithRouter';

Object.defineProperty(navigator, 'clipboard', {
  value: {
    writeText: () => {},
  },
});

const favoriteRecipes = '/favorite-recipes';
const emailInput = 'email-input';
const passwordInput = 'password-input';
const emailLiteral = 'test@trybe.com';
const imageString = 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg';
const btnFood = 'button-food';
const categoryDrinkString = 'Ordinary Drink';
const imageStringDrink = 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg';
const btnDrink = 'button-drink';
const alcohol = 'Optional alcohol';

jest.spyOn(navigator.clipboard, 'writeText');

describe('testes da página de favoritos', () => {
  test('se a receita favorita e copia o link da página de detalhes', async () => {
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    const corba = await screen.findAllByAltText('imagem da receita');
    userEvent.click(corba[0]);
    const btnStart = await screen.findByRole('button', { name: 'Start Recipe' });
    userEvent.click(btnStart);
    const btnFavorite = await screen.findByAltText('btn-favorite');
    expect(btnFavorite).toBeInTheDocument();
    userEvent.click(btnFavorite);
    history.push(favoriteRecipes);
    expect(history.location.pathname).toEqual(favoriteRecipes);
    const btnShare = await screen.findByTestId('0-horizontal-share-btn');
    expect(btnShare).toBeInTheDocument();
    userEvent.click(btnShare);
    expect(navigator.clipboard.writeText).toBeCalledTimes(1);
  });
  test('testa se ao clicar na imagem da comida a página é redirecionada', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const image = await screen.findByTestId(btnFood);
    const favorite = screen.getByText('Favorites');
    expect(favorite).toBeInTheDocument();
    expect(image).toBeInTheDocument();
    userEvent.click(image);
    await waitFor(() => expect(history.location.pathname).toBe('/meals/52977'));
  });
  test('testa se ao clicar no nome da comida a página é redirecionada', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const image = await screen.findByTestId('button-name-food');
    const favorite = screen.getByText('Favorites');
    expect(favorite).toBeInTheDocument();
    expect(image).toBeInTheDocument();
    userEvent.click(image);
    await waitFor(() => expect(history.location.pathname).toBe('/meals/52977'));
  });
  test('testa se ao clicar na imagem do drink a página é redirecionada', async () => {
    const object = [{ id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push('/favorite-recipes');
    const image = await screen.findByTestId(btnDrink);
    const favorite = screen.getByText('Favorites');
    expect(favorite).toBeInTheDocument();
    expect(image).toBeInTheDocument();
    userEvent.click(image);
    await waitFor(() => expect(history.location.pathname).toBe('/drinks/15997'));
  });
  test('testa se ao clicar na imagem do drink a página é redirecionada', async () => {
    const object = [{ id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const image = await screen.findByTestId('button-name-drink');
    const favorite = screen.getByText('Favorites');
    expect(favorite).toBeInTheDocument();
    expect(image).toBeInTheDocument();
    userEvent.click(image);
    await waitFor(() => expect(history.location.pathname).toBe('/drinks/15997'));
  });
  test('testa se ao clicar no filtro de drink só aparecerão drinks na página', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }, { id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const btnFilterDrink = await screen.findByTestId('filter-by-drink-btn');
    const recipeFood = await screen.findByTestId(btnFood);
    userEvent.click(btnFilterDrink);
    expect(recipeFood).not.toBeInTheDocument();
  });
  test('testa se ao clicar no filtro de meal só aparecerão meals na página', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }, { id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const btnFilterMeal = await screen.findByTestId('filter-by-meal-btn');
    const recipeDrink = await screen.findByTestId(btnDrink);
    userEvent.click(btnFilterMeal);
    expect(recipeDrink).not.toBeInTheDocument();
  });
  test('testa se ao clicar no filtro Alltodas receitas aparecerão na página', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }, { id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const btnFilterAll = await screen.findByTestId('filter-by-all-btn');
    const recipeDrink = await screen.findByTestId(btnDrink);
    const recipeFood = await screen.findByTestId(btnFood);
    userEvent.click(btnFilterAll);
    expect(recipeDrink).toBeInTheDocument();
    expect(recipeFood).toBeInTheDocument();
  });
  test('testa se ao clicar no botão de desfavoritar a comida, a receita desaparece da tela', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }, { id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const recipeFood = await screen.findByTestId(btnFood);
    const btnDisfavor = screen.getAllByAltText('black heart icon');
    userEvent.click(btnDisfavor[0]);
    expect(recipeFood).not.toBeInTheDocument();
  });
  test('testa se ao clicar no botão de desfavoritar a bebida, a receita desaparece da tela', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }, { id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const recipeDrink = await screen.findByTestId(btnDrink);
    const btnDisfavor = screen.getAllByAltText('black heart icon');
    userEvent.click(btnDisfavor[1]);
    expect(recipeDrink).not.toBeInTheDocument();
  });
  test('testa se ao clicar no botão de copiar a receita, a receita é copiada para o clipboard', async () => {
    const object = [{ id: '52977', type: 'meal', nationality: 'Turkish', category: 'Side', name: 'Corba', image: imageString, alcoholicOrNot: '' }, { id: '15997', type: 'drink', nationality: '', category: categoryDrinkString, name: 'GG', image: imageStringDrink, alcoholicOrNot: alcohol }];
    localStorage.setItem('favoriteRecipes', JSON.stringify(object));
    const { history } = renderWithRouter(<App />);
    const inputEmail = screen.getByTestId(emailInput);
    const inputPassword = screen.getByTestId(passwordInput);
    const button = screen.getByRole('button', { name: 'Enter' });
    userEvent.type(inputEmail, emailLiteral);
    userEvent.type(inputPassword, '1234567');
    userEvent.click(button);
    history.push(favoriteRecipes);
    const btnShare = await screen.findByTestId('1-horizontal-share-btn');
    userEvent.click(btnShare);
    expect(navigator.clipboard.writeText).toBeCalledTimes(1);
  });
});
